name: Unjumble
favicon: null
layout_spectrum: 0.50251
typography_spectrum: 0.834516562288627
title: Unjumble Me
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.3629778733011335
  saturation: 0.6601197200361639
  rhythmicContrast: 0.3119686765130609
purpose: []
